source "https://rubygems.org"

gem 'cucumber'
gem 'capybara'
# gem 'selenium-webdriver', '2.53.4'
gem 'selenium-webdriver'
gem 'rspec'
gem 'site_prism'
gem 'geckodriver-helper'
# gem 'faker'
gem 'cpf_faker'
# gem 'faker', github: 'stympy/faker'
gem 'faker', :git => 'https://github.com/stympy/faker', :branch => 'master'
gem 'sql_query'
# gem 'ruby-oci8', '2.2.5.1'
gem 'ruby-plsql'
gem 'ruby-oci8', '~> 2.2', '>= 2.2.7'
gem  'roo'
# gem 'faker', '~> 2.1', '>= 2.1.2'
